name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tags_comments_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''


    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: tags_comments_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin

    # Build backend
    - name: Build Backend
      working-directory: Tags_comments/Tags_comments
      run: mvn clean package -DskipTests

    # Run backend tests
    #- name: Run Backend Tests
    #  working-directory: Tags_comments/Tags_comments
    #  run: mvn test

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'npm'

    # Install frontend dependencies
    - name: Install Frontend Dependencies
      working-directory: Angular
      run: npm install

    # Lint frontend
    - name: Lint Frontend
      working-directory: Angular
      run: npx ng lint

    # Run frontend tests (Uncomment when I have frontend tests)
    #- name: Run Frontend Tests
    #  working-directory: Angular
    #  run: npx ng test --watch=false --browsers=ChromeHeadless

    # Build frontend
    - name: Build Frontend
      working-directory: Angular
      run: npx ng build --configuration production