name: Minimal CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:

    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/tags_comments_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 


    steps:
      # Step 1: Checkout your repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Step 3: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # Build backend
      - name: Build Backend
        working-directory: Tags_comments/Tags_comments
        run: mvn clean package -DskipTests


      # Wait for MySQL to be ready
      - name: Wait for MySQL
        run: sleep 30

      # Run backend tests
      - name: Run Backend Tests
        working-directory: Tags_comments/Tags_comments
        run: mvn test


      # Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: Angular
        run: npm install

      # Lint frontend
      # - name: Lint Frontend
      #   working-directory: Angular
      #   run: npx ng lint

      # Run frontend tests (if you have any)
      #- name: Run Frontend Tests
      #  working-directory: Angular
      #  run: npx ng test --watch=false --browsers=ChromeHeadless

      # Build frontend production bundle
      - name: Build Frontend
        working-directory: Angular
        run: npx ng build --configuration production



    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: tags_comments_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

        


